version: '3'

vars:
  BUCKET_NAME: rideoutlane.com
  REGION: us-east-1

tasks:
  build:
    desc: Build the React application
    cmds:
      - npm run build

  deploy:
    desc: Deploy to S3 bucket
    deps: [build]
    cmds:
      - echo "Deploying to {{.BUCKET_NAME}}..."
      # Deploy all files with proper content types and caching
      - aws s3 sync build/ s3://{{.BUCKET_NAME}} --delete --cache-control "public, max-age=31536000"
      # Update HTML files with no-cache
      - aws s3 cp build/index.html s3://{{.BUCKET_NAME}}/index.html --content-type "text/html; charset=utf-8" --cache-control "no-cache, no-store, must-revalidate"
      # Ensure CSS files have correct content type (using wildcard for dynamic filenames)
      - aws s3 cp build/static/css/main.*.css s3://{{.BUCKET_NAME}}/static/css/ --content-type "text/css; charset=utf-8" --cache-control "public, max-age=31536000"

  deploy:no-build:
    desc: Deploy to S3 bucket without building
    cmds:
      - task: deploy

  check:bucket:
    desc: Check S3 bucket configuration
    cmds:
      - aws s3api get-bucket-website --bucket {{.BUCKET_NAME}}
      - aws s3api get-bucket-policy --bucket {{.BUCKET_NAME}}

  list:bucket:
    desc: List contents of S3 bucket
    cmds:
      - aws s3 ls s3://{{.BUCKET_NAME}} --recursive

  clean:bucket:
    desc: Remove all files from S3 bucket
    interactive: true
    cmds:
      - aws s3 rm s3://{{.BUCKET_NAME}} --recursive

  setup:bucket:
    desc: Configure S3 bucket for static website hosting
    cmds:
      - |
        aws s3api put-bucket-website --bucket {{.BUCKET_NAME}} --website-configuration '{
          "IndexDocument": { "Suffix": "index.html" },
          "ErrorDocument": { "Key": "index.html" }
        }' 